"""GESTIMA - Konfigurace typů kroků"""

FEATURE_FIELDS = {
    # === SOUSTRUŽENÍ ===
    "face": {
        "name": "Zarovnání čela",
        "icon": "🔵",
        "category": "turning",
        "fields": ["from_diameter", "depth"],
        "cutting": ["Vc", "f", "Ap"],
        "db_operation": ("turning", "hrubovani"),
    },
    "od_rough": {
        "name": "Vnější hrubování",
        "icon": "🔄",
        "category": "turning",
        "fields": ["from_diameter", "to_diameter", "length"],
        "cutting": ["Vc", "f", "Ap"],
        "db_operation": ("turning", "hrubovani"),
    },
    "od_finish": {
        "name": "Vnější dokončení",
        "icon": "✨",
        "category": "turning",
        "fields": ["from_diameter", "to_diameter", "length"],
        "cutting": ["Vc", "f", "Ap"],
        "db_operation": ("turning", "dokoncovani"),
    },
    "id_rough": {
        "name": "Vnitřní hrubování",
        "icon": "🕳️",
        "category": "turning",
        "fields": ["from_diameter", "to_diameter", "length"],
        "cutting": ["Vc", "f", "Ap"],
        "db_operation": ("turning", "hrubovani"),
    },
    "id_finish": {
        "name": "Vnitřní dokončení",
        "icon": "💎",
        "category": "turning",
        "fields": ["from_diameter", "to_diameter", "length"],
        "cutting": ["Vc", "f", "Ap"],
        "db_operation": ("turning", "dokoncovani"),
    },
    "thread_od": {
        "name": "Vnější závit",
        "icon": "🔩",
        "category": "turning",
        "fields": ["from_diameter", "length", "thread_pitch"],
        "cutting": ["Vc"],
        "db_operation": ("threading", "zavitovani"),
    },
    "thread_id": {
        "name": "Vnitřní závit",
        "icon": "🔩",
        "category": "turning",
        "fields": ["from_diameter", "length", "thread_pitch"],
        "cutting": ["Vc"],
        "db_operation": ("threading", "zavitovani"),
    },
    "groove_od": {
        "name": "Vnější zápich",
        "icon": "➖",
        "category": "turning",
        "fields": ["from_diameter", "to_diameter", "width"],
        "cutting": ["Vc", "f"],
        "db_operation": ("grooving", "zapichovani"),
    },
    "od_profile": {
        "name": "Vnější profil",
        "icon": "🔄",
        "category": "turning",
        "fields": ["from_diameter", "to_diameter", "length"],
        "cutting": ["Vc", "f", "Ap"],
        "db_operation": ("turning", "hrubovani"),
    },
    "id_profile": {
        "name": "Vnitřní profil",
        "icon": "🕳️",
        "category": "turning",
        "fields": ["from_diameter", "to_diameter", "length"],
        "cutting": ["Vc", "f", "Ap"],
        "db_operation": ("turning", "hrubovani"),
    },
    "bore": {
        "name": "Vyvrtávání",
        "icon": "🕳️",
        "category": "turning",
        "fields": ["from_diameter", "to_diameter", "length"],
        "cutting": ["Vc", "f", "Ap"],
        "db_operation": ("turning", "hrubovani"),
    },
    "groove_id": {
        "name": "Vnitřní zápich",
        "icon": "➖",
        "category": "turning",
        "fields": ["from_diameter", "to_diameter", "width"],
        "cutting": ["Vc", "f"],
        "db_operation": ("grooving", "zapichovani"),
    },
    "groove_face": {
        "name": "Čelní zápich",
        "icon": "➖",
        "category": "turning",
        "fields": ["width", "depth"],
        "cutting": ["Vc", "f"],
        "db_operation": ("grooving", "zapichovani"),
    },
    "cutoff": {
        "name": "Odříznutí",
        "icon": "✂️",
        "category": "turning",
        "fields": ["from_diameter", "blade_width"],
        "cutting": ["Vc", "f"],
        "db_operation": ("parting", "upichnuti"),
    },
    "parting": {
        "name": "Upíchnutí",
        "icon": "✂️",
        "category": "turning",
        "fields": ["from_diameter", "blade_width"],
        "cutting": ["Vc", "f"],
        "db_operation": ("parting", "upichnuti"),
    },
    "chamfer": {
        "name": "Sražení hrany",
        "icon": "📐",
        "category": "turning",
        "fields": ["width", "from_diameter"],
        "cutting": ["Vc", "f"],
        "db_operation": ("turning", "dokoncovani"),
    },
    "radius": {
        "name": "Rádius",
        "icon": "📐",
        "category": "turning",
        "fields": ["corner_radius", "from_diameter"],
        "cutting": ["Vc", "f"],
        "db_operation": ("turning", "dokoncovani"),
    },
    "knurl": {
        "name": "Rýhování",
        "icon": "🔄",
        "category": "turning",
        "fields": ["from_diameter", "length"],
        "cutting": [],
        "constant_time": 2.0,
    },

    # === VRTÁNÍ ===
    "center_drill": {
        "name": "Navrtání",
        "icon": "🎯",
        "category": "drilling",
        "fields": ["to_diameter", "depth"],
        "cutting": ["Vc", "f"],
        "db_operation": ("drilling", "navrtani"),
    },
    "drill": {
        "name": "Vrtání",
        "icon": "🔘",
        "category": "drilling",
        "fields": ["to_diameter", "depth"],
        "cutting": ["Vc", "f"],
        "db_operation": ("drilling", "vrtani"),
    },
    "drill_deep": {
        "name": "Hluboké vrtání",
        "icon": "🔘",
        "category": "drilling",
        "fields": ["to_diameter", "depth"],
        "cutting": ["Vc", "f"],
        "db_operation": ("drilling", "vrtani_hluboke"),
    },
    "tap": {
        "name": "Závitování",
        "icon": "🔩",
        "category": "drilling",
        "fields": ["to_diameter", "depth", "thread_pitch"],
        "cutting": ["Vc"],
        "db_operation": ("threading", "zavitovani"),
    },
    "ream": {
        "name": "Vystružování",
        "icon": "🎯",
        "category": "drilling",
        "fields": ["to_diameter", "depth"],
        "cutting": ["Vc", "f"],
        "db_operation": ("drilling", "vystruzovani"),
    },

    # === LIVE TOOLING ===
    "lt_drill": {
        "name": "Příčné vrtání",
        "icon": "🔘",
        "category": "live_tooling",
        "fields": ["to_diameter", "depth", "count"],
        "cutting": ["Vc", "f"],
        "db_operation": ("drilling", "vrtani"),
    },
    "lt_drill_axial": {
        "name": "Axiální vrtání",
        "icon": "🔘",
        "category": "live_tooling",
        "fields": ["to_diameter", "depth", "count"],
        "cutting": ["Vc", "f"],
        "db_operation": ("drilling", "vrtani"),
    },
    "lt_tap": {
        "name": "Příčné závitování",
        "icon": "🔩",
        "category": "live_tooling",
        "fields": ["to_diameter", "depth", "thread_pitch"],
        "cutting": ["Vc"],
        "db_operation": ("threading", "zavitovani"),
    },
    "lt_flat": {
        "name": "Frézování plošky",
        "icon": "⬜",
        "category": "live_tooling",
        "fields": ["length", "width", "depth"],
        "cutting": ["Vc", "fz", "Ap"],
        "db_operation": ("milling", "frezovani"),
    },
    "lt_slot": {
        "name": "Drážka na soustruhu",
        "icon": "═",
        "category": "live_tooling",
        "fields": ["length", "width", "depth"],
        "cutting": ["Vc", "fz", "Ap"],
        "db_operation": ("milling", "frezovani"),
    },
    "lt_polygon": {
        "name": "Polygon",
        "icon": "⬡",
        "category": "live_tooling",
        "fields": ["from_diameter", "length", "count"],
        "cutting": ["Vc", "fz", "Ap"],
        "db_operation": ("milling", "frezovani"),
    },
    "lt_keyway": {
        "name": "Drážka pro pero (soustruh)",
        "icon": "═",
        "category": "live_tooling",
        "fields": ["length", "width", "depth"],
        "cutting": ["Vc", "fz", "Ap"],
        "db_operation": ("milling", "frezovani"),
    },
    "lt_contour": {
        "name": "Kontury (soustruh)",
        "icon": "〰️",
        "category": "live_tooling",
        "fields": ["length", "depth"],
        "cutting": ["Vc", "fz", "Ap"],
        "db_operation": ("milling", "frezovani"),
    },

    # === FRÉZOVÁNÍ ===
    "mill_face": {
        "name": "Frézování čela",
        "icon": "⬜",
        "category": "milling",
        "fields": ["length", "pocket_width", "depth"],
        "cutting": ["Vc", "fz", "Ap"],
        "db_operation": ("milling", "frezovani"),
    },
    "mill_pocket": {
        "name": "Kapsa",
        "icon": "⬜",
        "category": "milling",
        "fields": ["pocket_length", "pocket_width", "depth", "corner_radius"],
        "cutting": ["Vc", "fz", "Ap"],
        "db_operation": ("milling", "frezovani"),
    },
    "mill_slot": {
        "name": "Drážka",
        "icon": "═",
        "category": "milling",
        "fields": ["length", "width", "depth"],
        "cutting": ["Vc", "fz", "Ap"],
        "db_operation": ("milling", "frezovani"),
    },
    "mill_drill": {
        "name": "Vrtání",
        "icon": "🔘",
        "category": "milling",
        "fields": ["to_diameter", "depth", "count"],
        "cutting": ["Vc", "f"],
        "db_operation": ("drilling", "vrtani"),
    },
    "mill_shoulder": {
        "name": "Frézování osazení",
        "icon": "⬜",
        "category": "milling",
        "fields": ["length", "depth"],
        "cutting": ["Vc", "fz", "Ap"],
        "db_operation": ("milling", "frezovani"),
    },
    "mill_pocket_round": {
        "name": "Kruhová kapsa",
        "icon": "⭕",
        "category": "milling",
        "fields": ["to_diameter", "depth"],
        "cutting": ["Vc", "fz", "Ap"],
        "db_operation": ("milling", "frezovani"),
    },
    "mill_keyway": {
        "name": "Drážka pro pero",
        "icon": "═",
        "category": "milling",
        "fields": ["length", "width", "depth"],
        "cutting": ["Vc", "fz", "Ap"],
        "db_operation": ("milling", "frezovani"),
    },
    "mill_contour_od": {
        "name": "Vnější obrys",
        "icon": "〰️",
        "category": "milling",
        "fields": ["length", "depth"],
        "cutting": ["Vc", "fz", "Ap"],
        "db_operation": ("milling", "frezovani"),
    },
    "mill_contour_id": {
        "name": "Vnitřní obrys",
        "icon": "〰️",
        "category": "milling",
        "fields": ["length", "depth"],
        "cutting": ["Vc", "fz", "Ap"],
        "db_operation": ("milling", "frezovani"),
    },
    "mill_3d": {
        "name": "3D frézování",
        "icon": "🏔️",
        "category": "milling",
        "fields": ["length", "depth"],
        "cutting": ["Vc", "fz", "Ap"],
        "db_operation": ("milling", "frezovani"),
    },
    "mill_center": {
        "name": "Navrtání na frézce",
        "icon": "🎯",
        "category": "milling",
        "fields": ["to_diameter", "depth"],
        "cutting": ["Vc", "f"],
        "db_operation": ("drilling", "navrtani"),
    },
    "mill_drill_deep": {
        "name": "Hluboké vrtání na frézce",
        "icon": "🔘",
        "category": "milling",
        "fields": ["to_diameter", "depth"],
        "cutting": ["Vc", "f"],
        "db_operation": ("drilling", "vrtani_hluboke"),
    },
    "mill_ream": {
        "name": "Vystružování na frézce",
        "icon": "🎯",
        "category": "milling",
        "fields": ["to_diameter", "depth"],
        "cutting": ["Vc", "f"],
        "db_operation": ("drilling", "vystruzovani"),
    },
    "mill_tap": {
        "name": "Závitování na frézce",
        "icon": "🔩",
        "category": "milling",
        "fields": ["to_diameter", "depth", "thread_pitch"],
        "cutting": ["Vc"],
        "db_operation": ("threading", "zavitovani"),
    },
    "mill_thread": {
        "name": "Frézování závitu",
        "icon": "🔩",
        "category": "milling",
        "fields": ["to_diameter", "depth", "thread_pitch"],
        "cutting": ["Vc"],
        "db_operation": ("threading", "zavitovani"),
    },
    "mill_chamfer": {
        "name": "Sražení na frézce",
        "icon": "📐",
        "category": "milling",
        "fields": ["width", "from_diameter"],
        "cutting": ["Vc", "f"],
        "db_operation": ("milling", "frezovani"),
    },
    "mill_deburr": {
        "name": "Odjehlení na frézce",
        "icon": "✨",
        "category": "milling",
        "fields": [],
        "cutting": [],
        "constant_time": 2.0,
    },
    "mill_engrave": {
        "name": "Gravírování",
        "icon": "✏️",
        "category": "milling",
        "fields": [],
        "cutting": [],
        "constant_time": 5.0,
    },

    # === BROUŠENÍ ===
    "grind_od": {
        "name": "Broušení vnější",
        "icon": "🔵",
        "category": "grinding",
        "fields": ["from_diameter", "to_diameter", "length"],
        "cutting": ["Vc", "f", "Ap"],
        "db_operation": ("grinding", "brouseni"),
    },
    "grind_id": {
        "name": "Broušení vnitřní",
        "icon": "🔵",
        "category": "grinding",
        "fields": ["from_diameter", "to_diameter", "length"],
        "cutting": ["Vc", "f", "Ap"],
        "db_operation": ("grinding", "brouseni"),
    },
    "grind_face": {
        "name": "Broušení plochy",
        "icon": "🔵",
        "category": "grinding",
        "fields": ["from_diameter", "depth"],
        "cutting": ["Vc", "f", "Ap"],
        "db_operation": ("grinding", "brouseni"),
    },

    # === DOKONČOVACÍ ===
    "hone": {
        "name": "Honování",
        "icon": "💎",
        "category": "finishing",
        "fields": ["to_diameter", "length"],
        "cutting": [],
        "constant_time": 5.0,
    },
    "polish": {
        "name": "Leštění",
        "icon": "✨",
        "category": "finishing",
        "fields": [],
        "cutting": [],
        "constant_time": 3.0,
    },
    "deburr_manual": {
        "name": "Ruční odjehlení",
        "icon": "🔧",
        "category": "finishing",
        "fields": [],
        "cutting": [],
        "constant_time": 2.0,
    },

    # === LOGISTIKA ===
    "wash": {
        "name": "Mytí",
        "icon": "🚿",
        "category": "logistics",
        "fields": [],
        "cutting": [],
        "constant_time": 15.0,
    },
    "inspect": {
        "name": "Kontrola",
        "icon": "🔍",
        "category": "logistics",
        "fields": [],
        "cutting": [],
        "constant_time": 30.0,
    },
    "pack": {
        "name": "Balení",
        "icon": "📦",
        "category": "logistics",
        "fields": [],
        "cutting": [],
        "constant_time": 10.0,
    },
}
