"""add_quotes_and_quote_items_tables

Revision ID: 33932d9d878f
Revises: a8b9c0d1e2f3
Create Date: 2026-01-31 15:21:03.674456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33932d9d878f'
down_revision: Union[str, Sequence[str], None] = 'a8b9c0d1e2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.drop_column('stock_wall_thickness')
        batch_op.drop_column('stock_diameter')
        batch_op.drop_column('stock_length')
        batch_op.drop_column('stock_height')
        batch_op.drop_column('stock_width')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_width', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('stock_height', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('stock_length', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('stock_diameter', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('stock_wall_thickness', sa.REAL(), nullable=True))

    # ### end Alembic commands ###
