"""Initial schema: all tables from scratch

Revision ID: 78917f98a52d
Revises: 
Create Date: 2026-01-28 11:45:02.899236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78917f98a52d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cutting_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_group', sa.String(length=50), nullable=True),
    sa.Column('material_name', sa.String(length=200), nullable=True),
    sa.Column('operation_type', sa.String(length=50), nullable=True),
    sa.Column('operation', sa.String(length=50), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=True),
    sa.Column('Vc', sa.Float(), nullable=True),
    sa.Column('f', sa.Float(), nullable=True),
    sa.Column('Ap', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cutting_conditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cutting_conditions_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cutting_conditions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cutting_conditions_material_group'), ['material_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_cutting_conditions_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_cutting_conditions_operation'), ['operation'], unique=False)
        batch_op.create_index(batch_op.f('ix_cutting_conditions_operation_type'), ['operation_type'], unique=False)

    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('subtype', sa.String(length=50), nullable=True),
    sa.Column('max_bar_dia', sa.Float(), nullable=True),
    sa.Column('max_cut_diameter', sa.Float(), nullable=True),
    sa.Column('max_workpiece_dia', sa.Float(), nullable=True),
    sa.Column('max_workpiece_length', sa.Float(), nullable=True),
    sa.Column('min_workpiece_dia', sa.Float(), nullable=True),
    sa.Column('bar_feed_max_length', sa.Float(), nullable=True),
    sa.Column('has_bar_feeder', sa.Boolean(), nullable=True),
    sa.Column('has_milling', sa.Boolean(), nullable=True),
    sa.Column('max_milling_tools', sa.Integer(), nullable=True),
    sa.Column('has_sub_spindle', sa.Boolean(), nullable=True),
    sa.Column('axes', sa.Integer(), nullable=True),
    sa.Column('suitable_for_series', sa.Boolean(), nullable=True),
    sa.Column('suitable_for_single', sa.Boolean(), nullable=True),
    sa.Column('hourly_rate_amortization', sa.Float(), nullable=False),
    sa.Column('hourly_rate_labor', sa.Float(), nullable=False),
    sa.Column('hourly_rate_tools', sa.Float(), nullable=False),
    sa.Column('hourly_rate_overhead', sa.Float(), nullable=False),
    sa.Column('setup_base_min', sa.Float(), nullable=True),
    sa.Column('setup_per_tool_min', sa.Float(), nullable=True),
    sa.Column('default_k_machine', sa.Float(), nullable=True),
    sa.Column('default_k_operator', sa.Float(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machines_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_machines_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_id'), ['id'], unique=False)

    op.create_table('material_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_groups_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_material_groups_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_groups_id'), ['id'], unique=False)

    op.create_table('system_config',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value_float', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_config_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('material_norms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('w_nr', sa.String(length=50), nullable=True),
    sa.Column('en_iso', sa.String(length=50), nullable=True),
    sa.Column('csn', sa.String(length=50), nullable=True),
    sa.Column('aisi', sa.String(length=50), nullable=True),
    sa.Column('material_group_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_group_id'], ['material_groups.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_norms', schema=None) as batch_op:
        batch_op.create_index('idx_material_norms_group', ['material_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_norms_aisi'), ['aisi'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_norms_csn'), ['csn'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_norms_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_norms_en_iso'), ['en_iso'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_norms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_norms_material_group_id'), ['material_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_norms_w_nr'), ['w_nr'], unique=False)

    op.create_table('material_price_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('material_group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_group_id'], ['material_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_price_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_price_categories_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_material_price_categories_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_price_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_price_categories_material_group_id'), ['material_group_id'], unique=False)

    op.create_table('material_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_number', sa.String(length=7), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('shape', sa.Enum('ROUND_BAR', 'SQUARE_BAR', 'FLAT_BAR', 'HEXAGONAL_BAR', 'PLATE', 'TUBE', 'CASTING', 'FORGING', name='stockshape'), nullable=False),
    sa.Column('diameter', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('thickness', sa.Float(), nullable=True),
    sa.Column('wall_thickness', sa.Float(), nullable=True),
    sa.Column('weight_per_meter', sa.Float(), nullable=True),
    sa.Column('standard_length', sa.Float(), nullable=True),
    sa.Column('norms', sa.String(length=200), nullable=True),
    sa.Column('supplier_code', sa.String(length=50), nullable=True),
    sa.Column('supplier', sa.String(length=100), nullable=True),
    sa.Column('stock_available', sa.Float(), nullable=True),
    sa.Column('material_group_id', sa.Integer(), nullable=False),
    sa.Column('price_category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_group_id'], ['material_groups.id'], ),
    sa.ForeignKeyConstraint(['price_category_id'], ['material_price_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_items_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_material_items_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_items_material_number'), ['material_number'], unique=True)

    op.create_table('material_price_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_category_id', sa.Integer(), nullable=False),
    sa.Column('min_weight', sa.Float(), nullable=False),
    sa.Column('max_weight', sa.Float(), nullable=True),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['price_category_id'], ['material_price_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_price_tiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_price_tiers_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_price_tiers_id'), ['id'], unique=False)

    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=7), nullable=False),
    sa.Column('article_number', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('material_item_id', sa.Integer(), nullable=True),
    sa.Column('price_category_id', sa.Integer(), nullable=True),
    sa.Column('stock_shape', sa.Enum('ROUND_BAR', 'SQUARE_BAR', 'FLAT_BAR', 'HEXAGONAL_BAR', 'PLATE', 'TUBE', 'CASTING', 'FORGING', name='stockshape'), nullable=True),
    sa.Column('stock_diameter', sa.Float(), nullable=True),
    sa.Column('stock_length', sa.Float(), nullable=True),
    sa.Column('stock_width', sa.Float(), nullable=True),
    sa.Column('stock_height', sa.Float(), nullable=True),
    sa.Column('stock_wall_thickness', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('drawing_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_item_id'], ['material_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['price_category_id'], ['material_price_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parts_article_number'), ['article_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_parts_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_parts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parts_part_number'), ['part_number'], unique=True)

    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=7), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('unit_time_min', sa.Float(), nullable=True),
    sa.Column('material_cost', sa.Float(), nullable=True),
    sa.Column('machining_cost', sa.Float(), nullable=True),
    sa.Column('setup_cost', sa.Float(), nullable=True),
    sa.Column('overhead_cost', sa.Float(), nullable=True),
    sa.Column('margin_cost', sa.Float(), nullable=True),
    sa.Column('coop_cost', sa.Float(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('material_weight_kg', sa.Float(), nullable=True),
    sa.Column('material_price_per_kg', sa.Float(), nullable=True),
    sa.Column('is_frozen', sa.Boolean(), nullable=False),
    sa.Column('frozen_at', sa.DateTime(), nullable=True),
    sa.Column('frozen_by_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_data', sa.JSON(), nullable=True),
    sa.Column('unit_price_frozen', sa.Float(), nullable=True),
    sa.Column('total_price_frozen', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['frozen_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batches_batch_number'), ['batch_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_batches_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_frozen_by_id'), ['frozen_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_is_frozen'), ['is_frozen'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_part_id'), ['part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_unit_price_frozen'), ['unit_price_frozen'], unique=False)

    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('cutting_mode', sa.String(length=10), nullable=True),
    sa.Column('setup_time_min', sa.Float(), nullable=True),
    sa.Column('operation_time_min', sa.Float(), nullable=True),
    sa.Column('setup_time_locked', sa.Boolean(), nullable=True),
    sa.Column('operation_time_locked', sa.Boolean(), nullable=True),
    sa.Column('is_coop', sa.Boolean(), nullable=True),
    sa.Column('coop_type', sa.String(length=50), nullable=True),
    sa.Column('coop_price', sa.Float(), nullable=True),
    sa.Column('coop_min_price', sa.Float(), nullable=True),
    sa.Column('coop_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operations_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_part_id'), ['part_id'], unique=False)

    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('feature_type', sa.Enum('FACE', 'OD_ROUGH', 'OD_FINISH', 'OD_PROFILE', 'ID_ROUGH', 'ID_FINISH', 'ID_PROFILE', 'BORE', 'THREAD_OD', 'THREAD_ID', 'GROOVE_OD', 'GROOVE_ID', 'GROOVE_FACE', 'PARTING', 'CUTOFF', 'CHAMFER', 'RADIUS', 'KNURL', 'CENTER_DRILL', 'DRILL', 'DRILL_DEEP', 'REAM', 'TAP', 'LT_DRILL', 'LT_DRILL_AXIAL', 'LT_TAP', 'LT_FLAT', 'LT_SLOT', 'LT_POLYGON', 'LT_KEYWAY', 'LT_CONTOUR', 'MILL_FACE', 'MILL_SHOULDER', 'MILL_POCKET', 'MILL_POCKET_ROUND', 'MILL_SLOT', 'MILL_KEYWAY', 'MILL_CONTOUR_OD', 'MILL_CONTOUR_ID', 'MILL_3D', 'MILL_CENTER', 'MILL_DRILL', 'MILL_DRILL_DEEP', 'MILL_REAM', 'MILL_TAP', 'MILL_THREAD', 'MILL_CHAMFER', 'MILL_DEBURR', 'MILL_ENGRAVE', 'GRIND_OD', 'GRIND_ID', 'GRIND_FACE', 'HONE', 'POLISH', 'DEBURR_MANUAL', 'WASH', 'INSPECT', 'PACK', name='featuretype'), nullable=True),
    sa.Column('from_diameter', sa.Float(), nullable=True),
    sa.Column('to_diameter', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('depth', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('pocket_length', sa.Float(), nullable=True),
    sa.Column('pocket_width', sa.Float(), nullable=True),
    sa.Column('corner_radius', sa.Float(), nullable=True),
    sa.Column('thread_pitch', sa.Float(), nullable=True),
    sa.Column('Vc', sa.Float(), nullable=True),
    sa.Column('f', sa.Float(), nullable=True),
    sa.Column('Ap', sa.Float(), nullable=True),
    sa.Column('fz', sa.Float(), nullable=True),
    sa.Column('Vc_locked', sa.Boolean(), nullable=True),
    sa.Column('f_locked', sa.Boolean(), nullable=True),
    sa.Column('Ap_locked', sa.Boolean(), nullable=True),
    sa.Column('blade_width', sa.Float(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('predicted_time_sec', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_features_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_features_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_features_operation_id'), ['operation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_features_operation_id'))
        batch_op.drop_index(batch_op.f('ix_features_id'))
        batch_op.drop_index(batch_op.f('ix_features_deleted_at'))

    op.drop_table('features')
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operations_part_id'))
        batch_op.drop_index(batch_op.f('ix_operations_id'))
        batch_op.drop_index(batch_op.f('ix_operations_deleted_at'))

    op.drop_table('operations')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_unit_price_frozen'))
        batch_op.drop_index(batch_op.f('ix_batches_part_id'))
        batch_op.drop_index(batch_op.f('ix_batches_is_frozen'))
        batch_op.drop_index(batch_op.f('ix_batches_id'))
        batch_op.drop_index(batch_op.f('ix_batches_frozen_by_id'))
        batch_op.drop_index(batch_op.f('ix_batches_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_batches_batch_number'))

    op.drop_table('batches')
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parts_part_number'))
        batch_op.drop_index(batch_op.f('ix_parts_id'))
        batch_op.drop_index(batch_op.f('ix_parts_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_parts_article_number'))

    op.drop_table('parts')
    with op.batch_alter_table('material_price_tiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_price_tiers_id'))
        batch_op.drop_index(batch_op.f('ix_material_price_tiers_deleted_at'))

    op.drop_table('material_price_tiers')
    with op.batch_alter_table('material_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_items_material_number'))
        batch_op.drop_index(batch_op.f('ix_material_items_id'))
        batch_op.drop_index(batch_op.f('ix_material_items_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_material_items_code'))

    op.drop_table('material_items')
    with op.batch_alter_table('material_price_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_price_categories_material_group_id'))
        batch_op.drop_index(batch_op.f('ix_material_price_categories_id'))
        batch_op.drop_index(batch_op.f('ix_material_price_categories_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_material_price_categories_code'))

    op.drop_table('material_price_categories')
    with op.batch_alter_table('material_norms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_norms_w_nr'))
        batch_op.drop_index(batch_op.f('ix_material_norms_material_group_id'))
        batch_op.drop_index(batch_op.f('ix_material_norms_id'))
        batch_op.drop_index(batch_op.f('ix_material_norms_en_iso'))
        batch_op.drop_index(batch_op.f('ix_material_norms_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_material_norms_csn'))
        batch_op.drop_index(batch_op.f('ix_material_norms_aisi'))
        batch_op.drop_index('idx_material_norms_group')

    op.drop_table('material_norms')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))

    op.drop_table('users')
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_config_deleted_at'))

    op.drop_table('system_config')
    with op.batch_alter_table('material_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_groups_id'))
        batch_op.drop_index(batch_op.f('ix_material_groups_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_material_groups_code'))

    op.drop_table('material_groups')
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machines_id'))
        batch_op.drop_index(batch_op.f('ix_machines_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_machines_code'))

    op.drop_table('machines')
    with op.batch_alter_table('cutting_conditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cutting_conditions_operation_type'))
        batch_op.drop_index(batch_op.f('ix_cutting_conditions_operation'))
        batch_op.drop_index(batch_op.f('ix_cutting_conditions_mode'))
        batch_op.drop_index(batch_op.f('ix_cutting_conditions_material_group'))
        batch_op.drop_index(batch_op.f('ix_cutting_conditions_id'))
        batch_op.drop_index(batch_op.f('ix_cutting_conditions_deleted_at'))

    op.drop_table('cutting_conditions')
    # ### end Alembic commands ###
