<script setup lang="ts">
import { ref, computed } from 'vue'
import { usePartsStore } from '@/stores/parts'
import type { PartCreate, Part } from '@/types/part'
import { drawingsApi } from '@/api/drawings'
import DragDropZone from '@/components/ui/DragDropZone.vue'
import PDFPreview from '@/components/ui/PDFPreview.vue'
import { Trash2, Check, X } from 'lucide-vue-next'
import { ICON_SIZE } from '@/config/design'

const emit = defineEmits<{
  'created': [part: Part]
  'cancel': []
}>()

const partsStore = usePartsStore()

const formData = ref<PartCreate>({
  article_number: '',
  name: '',
  customer_revision: '',
  drawing_number: ''
})

// Drawing upload state (file held locally, uploaded after part creation)
const tempDrawingFile = ref<File | null>(null)
const uploadingDrawing = ref(false)
const uploadError = ref<string | null>(null)

const hasTempDrawing = computed(() => tempDrawingFile.value !== null)
const tempDrawingUrl = computed(() => {
  if (!tempDrawingFile.value) return ''
  return URL.createObjectURL(tempDrawingFile.value)
})

function handleDrawingSelected(file: File) {
  tempDrawingFile.value = file
  uploadError.value = null
}

function handleDrawingError(message: string) {
  uploadError.value = message
}

function removeTempDrawing() {
  tempDrawingFile.value = null
  uploadError.value = null
}

async function handleSubmit() {
  try {
    // 1. Create part (part_number auto-generated by backend)
    const created = await partsStore.createPart(formData.value)

    // 2. Upload drawing via drawings API if file was selected
    if (tempDrawingFile.value) {
      uploadingDrawing.value = true
      try {
        await drawingsApi.uploadDrawing(created.part_number, tempDrawingFile.value)
      } catch (error: any) {
        // Part was created but drawing upload failed — notify but don't block
        console.warn('Drawing upload failed after part creation:', error.message)
      } finally {
        uploadingDrawing.value = false
      }
    }

    // Reset form
    formData.value = { article_number: '', name: '', customer_revision: '', drawing_number: '' }
    tempDrawingFile.value = null
    uploadError.value = null

    emit('created', created)
  } catch (error) {
    throw error
  }
}

function handleCancel() {
  formData.value = { article_number: '', name: '', customer_revision: '', drawing_number: '' }
  tempDrawingFile.value = null
  uploadError.value = null
  emit('cancel')
}
</script>

<template>
  <div class="part-create-form">
    <h2>Nový díl</h2>

    <form @submit.prevent="handleSubmit">
      <!-- Part number auto-generated (10XXXXXX) -->

      <div class="form-fields">
        <div class="form-field">
          <label class="field-label">Artikl *</label>
          <input v-model="formData.article_number" required placeholder="Dodavatelské číslo" class="field-input" />
        </div>

        <div class="form-field">
          <label class="field-label">Číslo výkresu</label>
          <input v-model="formData.drawing_number" placeholder="Číslo výkresu" class="field-input" />
        </div>

        <div class="form-field">
          <label class="field-label">Název *</label>
          <input v-model="formData.name" required placeholder="Název dílu" class="field-input" />
        </div>

        <div class="form-field">
          <label class="field-label">Revize</label>
          <input v-model="formData.customer_revision" placeholder="Zákaznická revize" class="field-input" />
        </div>
      </div>

      <!-- Drawing upload (temp) -->
      <div class="form-field drawing-field">
        <label>Výkres (PDF)</label>

        <!-- No temp drawing - show upload zone -->
        <div v-if="!hasTempDrawing">
          <DragDropZone
            :model-value="tempDrawingFile"
            accept="application/pdf"
            :max-size="10 * 1024 * 1024"
            label="Nahrajte PDF výkres (volitelné)"
            :loading="uploadingDrawing"
            @upload="handleDrawingSelected"
            @error="handleDrawingError"
          />
          <p v-if="uploadError" class="upload-error">{{ uploadError }}</p>
        </div>

        <!-- Has temp drawing - show preview -->
        <div v-else class="temp-drawing-preview">
          <PDFPreview
            :src="tempDrawingUrl"
            width="120px"
            height="160px"
            :clickable="false"
          />
          <div class="temp-drawing-info">
            <p class="temp-filename">{{ tempDrawingFile?.name }}</p>
            <button type="button" class="btn-sm btn-danger" @click="removeTempDrawing">
              <Trash2 :size="ICON_SIZE.SMALL" />
              Odebrat
            </button>
          </div>
        </div>
      </div>

      <div class="form-actions">
        <button type="button" @click="handleCancel" class="icon-btn icon-btn-danger" title="Zrušit">
          <X :size="ICON_SIZE.STANDARD" />
        </button>
        <button type="submit" class="icon-btn icon-btn-success" title="Vytvořit díl">
          <Check :size="ICON_SIZE.STANDARD" />
        </button>
      </div>
    </form>
  </div>
</template>

<style scoped>
.part-create-form {
  display: flex;
  flex-direction: column;
  gap: var(--space-6);
  max-width: 600px;
}

.part-create-form h2 {
  margin: 0;
  font-size: var(--text-2xl);
  font-weight: var(--font-semibold);
  color: var(--text-primary);
}

/* Vertical form fields */
.form-fields {
  display: flex;
  flex-direction: column;
  gap: var(--space-3);
  padding: var(--space-4);
  background: var(--bg-surface);
  border: 1px solid var(--border-default);
  border-radius: var(--radius-md);
  position: relative;
}

.form-field {
  display: flex;
  flex-direction: column;
  gap: var(--space-1);
}

.field-label {
  font-size: var(--text-sm);
  font-weight: var(--font-medium);
  color: var(--text-secondary);
}

.field-input {
  padding: var(--space-2) var(--space-3);
  border: 1px solid var(--border-default);
  border-radius: var(--radius-md);
  font-size: var(--text-base);
  background: var(--bg-input);
  color: var(--text-body);
  transition: var(--transition-fast);
}

.field-input:focus {
  outline: none;
  background: var(--state-focus-bg);
  border-color: var(--state-focus-border);
}

.form-actions {
  display: flex;
  gap: var(--space-2);
  justify-content: flex-end;
  padding: var(--space-3) var(--space-4);
  background: var(--bg-surface);
  border: 1px solid var(--border-default);
  border-radius: var(--radius-md);
}

/* Icon buttons use global .icon-btn classes from design-system.css */

/* Drawing field */
.drawing-field {
  grid-column: 1 / -1;
}

.upload-error {
  margin-top: var(--space-2);
  padding: var(--space-2) var(--space-3);
  font-size: var(--text-sm);
  color: var(--color-danger);
  background: rgba(244, 63, 94, 0.05);
  border: 1px solid var(--color-danger);
  border-radius: var(--radius-sm);
}

.temp-drawing-preview {
  display: flex;
  align-items: flex-start;
  gap: var(--space-3);
  padding: var(--space-3);
  background: var(--bg-surface);
  border: 1px solid var(--border-default);
  border-radius: var(--radius-md);
}

.temp-drawing-info {
  display: flex;
  flex-direction: column;
  gap: var(--space-2);
}

.temp-filename {
  margin: 0;
  font-size: var(--text-sm);
  font-weight: var(--font-medium);
  color: var(--text-body);
  word-break: break-word;
}

/* Button styles removed - using global design-system.css utilities */
/* See: frontend/src/assets/css/design-system.css for .btn-primary, .btn-secondary */
</style>
